# Generated by Django 5.0.3 on 2024-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productmodel_productmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
